"""Create a baseline migrations

Revision ID: 0f25d63f1d67
Revises: 
Create Date: 2024-03-15 14:59:53.178773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f25d63f1d67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flat_chat',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('visit_id', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('suggestion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flat_chat')
    # ### end Alembic commands ###
